# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tugas

on:
  push:
    branches: [ task ]

jobs:
  build:
    services:
      nats:
        image: nats
        ports:
          - 4222:4222
      redis:
        image: redis
        ports:
          - 6379:6379
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        ports:
          - 9000:9000
        options: --name minio-server
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    env:
      tm_database__password: ${{ secrets.POSTGRES_PASSWORD }}
      tm_database__database: ${{ secrets.POSTGRES_DB }}
      tm_server__workerPort: ${{ secrets.WORKER_PORT }}
      tm_server__taskPort: ${{ secrets.WORKER_PORT }}
      tm_server__performancePort: ${{ secrets.WORKER_PORT }}
    defaults:
      run:
        working-directory: ./tugas
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Run Install Dependencies
      run: npm i
    - name: Run Test Linter
      run: npm run lint
    - name: Run Integration Test
      run: npm run test:tasks
